-- 0014_skill_runtime_lite_v1.sql
-- Generated by scripts/compile-runtimes.mjs - DO NOT EDIT MANUALLY

-- =====================================================================
-- 1. SKILL RUNTIME VERSIONS
-- =====================================================================

CREATE TABLE IF NOT EXISTS skill_runtime_versions (
  id TEXT PRIMARY KEY,
  skill_definition_id TEXT NOT NULL,
  runtime_version INTEGER NOT NULL,
  runtime_status TEXT NOT NULL CHECK (
    runtime_status IN (
      'draft',
      'active',
      'deprecated',
      'disabled'
    )
  ),
  runtime_type TEXT NOT NULL DEFAULT 'prompt',
  system_instructions TEXT NOT NULL,
  execution_steps_json TEXT NOT NULL DEFAULT '[]',
  input_schema_json TEXT NOT NULL DEFAULT '{}',
  output_schema_json TEXT NOT NULL DEFAULT '{}',
  tool_policy_json TEXT NOT NULL DEFAULT '{}',
  safety_policy_json TEXT NOT NULL DEFAULT '{}',
  level_effects_json TEXT NOT NULL DEFAULT '{}',
  checksum TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  activated_at TEXT,
  deprecated_at TEXT,
  FOREIGN KEY (skill_definition_id)
    REFERENCES agent_skill_definitions(id),
  UNIQUE(skill_definition_id, runtime_version)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_active_runtime
  ON skill_runtime_versions(skill_definition_id)
  WHERE runtime_status = 'active';

CREATE INDEX IF NOT EXISTS idx_runtime_versions_def
  ON skill_runtime_versions(skill_definition_id);

-- =====================================================================
-- 2. SKILL RUNTIME EXECUTIONS
-- =====================================================================

CREATE TABLE IF NOT EXISTS skill_runtime_executions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  agent_id TEXT NOT NULL,
  task_type TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  request_hash TEXT NOT NULL,
  status TEXT NOT NULL CHECK (
    status IN ('pending', 'running', 'completed', 'failed', 'timed_out', 'cancelled')
  ),
  selected_skills_json TEXT NOT NULL DEFAULT '[]',
  input_json TEXT NOT NULL DEFAULT '{}',
  result_json TEXT NOT NULL DEFAULT '{}',
  input_tokens INTEGER NOT NULL DEFAULT 0,
  output_tokens INTEGER NOT NULL DEFAULT 0,
  estimated_cost_usd_micros INTEGER NOT NULL DEFAULT 0,
  model_name TEXT NOT NULL,
  retry_count INTEGER NOT NULL DEFAULT 0,
  error_code TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  started_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TEXT,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (agent_id) REFERENCES agents(id),
  UNIQUE(user_id, agent_id, idempotency_key)
);

-- =====================================================================
-- 3. TASK SKILL RUNTIME USAGES (Audit)
-- =====================================================================

CREATE TABLE IF NOT EXISTS task_skill_runtime_usages (
  id TEXT PRIMARY KEY,
  task_execution_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  agent_id TEXT NOT NULL,
  learned_skill_id TEXT NOT NULL,
  skill_definition_id TEXT NOT NULL,
  runtime_version_id TEXT NOT NULL,
  runtime_version INTEGER NOT NULL,
  learned_skill_level INTEGER NOT NULL,
  selection_role TEXT NOT NULL CHECK (
    selection_role IN ('required', 'recommended', 'fallback')
  ),
  trigger_reason TEXT,
  runtime_checksum TEXT NOT NULL,
  input_tokens INTEGER NOT NULL DEFAULT 0,
  output_tokens INTEGER NOT NULL DEFAULT 0,
  estimated_cost_usd_micros INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL CHECK (
    status IN ('selected', 'loaded', 'completed', 'failed', 'skipped')
  ),
  error_code TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TEXT,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (agent_id) REFERENCES agents(id),
  FOREIGN KEY (learned_skill_id) REFERENCES agent_learned_skills(id),
  FOREIGN KEY (skill_definition_id) REFERENCES agent_skill_definitions(id),
  FOREIGN KEY (runtime_version_id) REFERENCES skill_runtime_versions(id),
  FOREIGN KEY (task_execution_id) REFERENCES skill_runtime_executions(id),
  UNIQUE(task_execution_id, learned_skill_id, runtime_version_id)
);

CREATE INDEX IF NOT EXISTS idx_runtime_usages_execution
  ON task_skill_runtime_usages(task_execution_id);

-- =====================================================================
-- 4. SEED DATA FOR 8 ACTIVE RUNTIMES
-- =====================================================================

INSERT OR IGNORE INTO skill_runtime_versions (
  id,
  skill_definition_id,
  runtime_version,
  runtime_status,
  runtime_type,
  system_instructions,
  tool_policy_json,
  level_effects_json,
  checksum,
  created_at,
  activated_at
) VALUES (
  'sd_aut_task_decomposition_v1',
  'sd_aut_task_decomposition',
  1,
  'active',
  'prompt',
  '# Purpose
To break down complex objectives into structured, ordered, and executable sub-tasks.

# Use When
Planning a multi-step workflow or task execution path.

# Do Not Use When
The workflow is a simple single-step action or requires real-time reactive recovery (use Failure Recovery instead).

# Required Inputs
* `objective`: The primary goal to achieve.
* `constraints`: Limits and rules governing the execution.
* `deadline`: Time limits for the task.
* `tools`: Allowed tools.
* `budget`: Budget limits (GP or usd).

# Execution Procedure
1. Analyze the main objective and identify constraints.
2. Outline the necessary milestones and step dependencies.
3. For each step, define clear inputs, expected output, and verification check.
4. Assess risks for each individual step.
5. Order steps sequentially based on dependencies.
6. Strictly avoid creating redundant or unnecessary steps.

# Output Contract
The final output must be structured JSON containing:
* `steps`: Array of objects, each containing:
  - `step_id`: String identifier (e.g. step_1).
  - `goal`: What this step accomplishes.
  - `dependencies`: List of step_ids this step depends on.
  - `inputs`: Data required for this step.
  - `expected_output`: What this step must produce.
  - `verification`: Criteria to verify step success.
  - `risk`: Assessment of failure risks.

# Verification Checklist
- Confirm all steps are necessary to reach the objective.
- Verify no step violates budget or deadline constraints.
- Confirm dependency order is correct.

# Failure Handling
If constraints cannot be met within the budget/deadline, fail early with detailed explanation.

# Safety Boundaries
- Do not create unnecessary steps.
- Do not exceed user permissions.
- Do not auto-approve funds or budget spending.
- Do not execute high-risk operations automatically.

# Level Effects
- Level 1: Basic execution procedure.
- Level 2: Identifies critical path steps.
- Level 3: Adds risk mitigation plans for high-risk steps.
- Level 4: Conducts resource constraint optimization.
- Level 5: Performs dependency loop check.',
  '{"allowed_tools":["task_planner"],"forbidden_actions":["auto_approve_funding","execute_high_risk_actions","exceed_permissions"]}',
  '{"1":"Basic execution procedure.","2":"Identifies critical path steps.","3":"Adds risk mitigation plans for high-risk steps.","4":"Conducts resource constraint optimization.","5":"Performs dependency loop check."}',
  'bf379a2c267599cc6f921836e57daf239fac3d62ca4eb08908a06a4a456a3536',
  '2026-06-22 00:00:00',
  '2026-06-22 00:00:00'
);

INSERT OR IGNORE INTO skill_runtime_versions (
  id,
  skill_definition_id,
  runtime_version,
  runtime_status,
  runtime_type,
  system_instructions,
  tool_policy_json,
  level_effects_json,
  checksum,
  created_at,
  activated_at
) VALUES (
  'sd_con_structured_writing_v1',
  'sd_con_structured_writing',
  1,
  'active',
  'prompt',
  '# Purpose
To write structured, clear, and professional text based on a specified topic and format.

# Use When
Drafting a structured brief, report, specification, checklist, or proposal.

# Do Not Use When
The primary task is checking facts or verifying source documents (this skill focuses on structure and writing, not verification).

# Required Inputs
* `topic`: The core subject matter.
* `audience`: The target demographic or profile of the reader.
* `format`: The type of document (must be one of: `brief`, `report`, `specification`, `checklist`, `proposal`).
* `tone`: Desired voice and style (e.g. professional, concise).
* `requiredSections`: List of headings or areas that must be covered.

# Execution Procedure
1. Create a logical outline of the document.
2. Structure the content hierarchically using appropriate heading levels.
3. Keep the text concise and eliminate repetitive phrases or ideas.
4. Mark any placeholder information or facts needing confirmation with a clear warning or tag.
5. Generate the complete formatted document following the requested structure.

# Output Contract
The final output must be structured JSON containing:
* `title`: Document title.
* `outline`: The hierarchy structure of the document.
* `sections`: Array of objects with section headers and text content.
* `unverified_facts`: List of statements requiring fact-checking or verification.
* `formatted_content`: Full text output.

# Verification Checklist
- Confirm all required sections are present.
- Verify that formatting matches one of the supported formats.
- Ensure any unverified statements are explicitly flagged.

# Failure Handling
If required inputs are incomplete, halt generation.

# Safety Boundaries
- Do not make final claims without flagging unverified statements.

# Level Effects
- Level 1: Basic execution procedure.
- Level 2: Adds transition phrases and style polish.
- Level 3: Formulates custom introduction and summary sections.
- Level 4: Enhances formatting with checklists and inline highlights.
- Level 5: Performs readability and flow review.',
  '{"allowed_tools":[],"forbidden_actions":["perform_fact_checking"]}',
  '{"1":"Basic execution procedure.","2":"Adds transition phrases and style polish.","3":"Formulates custom introduction and summary sections.","4":"Enhances formatting with checklists and inline highlights.","5":"Performs readability and flow review."}',
  '5554d34164d381c7ab0b955f54ff1b4e71451bfaec178e491b44805ccc3e9244',
  '2026-06-22 00:00:00',
  '2026-06-22 00:00:00'
);

INSERT OR IGNORE INTO skill_runtime_versions (
  id,
  skill_definition_id,
  runtime_version,
  runtime_status,
  runtime_type,
  system_instructions,
  tool_policy_json,
  level_effects_json,
  checksum,
  created_at,
  activated_at
) VALUES (
  'sd_exp_failure_recovery_v1',
  'sd_exp_failure_recovery',
  1,
  'active',
  'prompt',
  '# Purpose
To handle task step failures and execute recovery plans without compromising security boundaries.

# Use When
A step in the workflow fails or returns an error.

# Do Not Use When
The task is executing normally or during initial planning (use Task Decomposition instead).

# Required Inputs
* `failedStep`: Details of the step that failed.
* `errorMessage`: The error details or code.
* `context`: System state and constraints.

# Execution Procedure
1. Identify the type and root cause of the failure.
2. Determine if the error is temporary (retryable).
3. Attempt at most one retry with the exact same method.
4. If retry fails, switch to alternative sources, tools, or methods.
5. If alternatives fail, downgrade the output gracefully (e.g. partial results).
6. If the task cannot proceed safely, pause execution.
7. Return issues requiring user confirmation.

# Output Contract
The final output must be structured JSON containing:
* `failure_type`: Classified type of failure.
* `recovery_action`: Action taken (e.g. retry, alternative, downgrade, pause).
* `retry_attempted`: Boolean indicating if retry was executed.
* `status`: One of `recovered`, `degraded`, `paused`, `failed`.
* `user_action_required`: Prompt for user confirmation if paused.
* `notes`: Explanation of recovery steps.

# Verification Checklist
- Confirm no more than one identical retry was attempted.
- Ensure permissions or budgets were not expanded.
- Verify user action request is clear if paused.

# Failure Handling
If recovery actions fail or are unsafe, immediately pause and request user intervention.

# Safety Boundaries
- Never retry infinitely.
- Never hide or ignore failures.
- Do not expand permissions.
- Do not authorize payments or fees.
- Do not sign or transfer assets automatically.

# Level Effects
- Level 1: Basic execution procedure.
- Level 2: Adds failure classification diagnostics.
- Level 3: Implements backoff retry policies.
- Level 4: Formulates fallback method tree.
- Level 5: Performs security boundary check before recovery execution.',
  '{"allowed_tools":[],"forbidden_actions":["infinite_retry","hide_failure","expand_permissions","auto_sign_transaction"]}',
  '{"1":"Basic execution procedure.","2":"Adds failure classification diagnostics.","3":"Implements backoff retry policies.","4":"Formulates fallback method tree.","5":"Performs security boundary check before recovery execution."}',
  'b0e2db6da9b0b22f7e20883f331573e44f81b56919e71fd46a85abfe9d5e8666',
  '2026-06-22 00:00:00',
  '2026-06-22 00:00:00'
);

INSERT OR IGNORE INTO skill_runtime_versions (
  id,
  skill_definition_id,
  runtime_version,
  runtime_status,
  runtime_type,
  system_instructions,
  tool_policy_json,
  level_effects_json,
  checksum,
  created_at,
  activated_at
) VALUES (
  'sd_res_information_summary_v1',
  'sd_res_information_summary',
  1,
  'active',
  'prompt',
  '# Purpose
To synthesize information from multiple sources into a single, cohesive, and actionable summary.

# Use When
Combining multiple research inputs, reports, or articles to support decision making.

# Do Not Use When
The input materials are insufficient or when external fact verification is the primary task.

# Required Inputs
* `materials`: Array of texts or links containing target information.
* `targetAudience`: The intended reader of the synthesized output.
* `decisionGoal`: The specific decision or action this synthesis aims to support.
* `outputLength`: Preferred length or constraint for the output.

# Execution Procedure
1. Deduplicate redundant data across all input materials.
2. Identify overlapping facts and themes.
3. Detect and mark any conflicting statements or contradictions.
4. Extract key findings and conclusions aligned with the decision goal.
5. Formulate actionable recommendations.
6. Strictly avoid introducing any external facts not supported by the input materials.

# Output Contract
The final output must be structured JSON containing:
* `summary`: A concise high-level synthesis of all materials.
* `key_findings`: List of critical findings backed by the inputs.
* `conflicts`: List of any contradictions found between sources.
* `decision_points`: Identified options or variables key to the decision.
* `recommended_actions`: Steps recommended based on the synthesis.

# Verification Checklist
- Confirm all points in `key_findings` can be traced back to the input materials.
- Ensure no external facts or assumptions are introduced.
- Verify conflicts are clearly marked.

# Failure Handling
If materials are missing or empty, abort execution. If materials are contradictory, highlight them in the `conflicts` field.

# Safety Boundaries
- Never introduce any information or facts that do not exist in the input materials.

# Level Effects
- Level 1: Basic execution procedure.
- Level 2: Adds a cross-referencing matrix for findings.
- Level 3: Formulates options analysis for each decision point.
- Level 4: Adds detailed risk assessment to recommendations.
- Level 5: Performs final self-check on external fact leaks.',
  '{"allowed_tools":[],"forbidden_actions":["introduce_external_facts"]}',
  '{"1":"Basic execution procedure.","2":"Adds a cross-referencing matrix for findings.","3":"Formulates options analysis for each decision point.","4":"Adds detailed risk assessment to recommendations.","5":"Performs final self-check on external fact leaks."}',
  'fa012366e79e0998a6a3e1d9e73c1bf457076938842ebee90a7acf162f0ce2ab',
  '2026-06-22 00:00:00',
  '2026-06-22 00:00:00'
);

INSERT OR IGNORE INTO skill_runtime_versions (
  id,
  skill_definition_id,
  runtime_version,
  runtime_status,
  runtime_type,
  system_instructions,
  tool_policy_json,
  level_effects_json,
  checksum,
  created_at,
  activated_at
) VALUES (
  'sd_res_project_research_v1',
  'sd_res_project_research',
  1,
  'active',
  'prompt',
  '# Purpose
To gather and analyze context about a specific project from online sources to build a robust profile.

# Use When
Conducting primary research on a crypto project, startup, protocol, or product.

# Do Not Use When
The project requires real-time transaction processing or execution of actions on-chain.

# Required Inputs
* `projectName`: The name of the project.
* `url`: The official URL of the project.
* `researchGoal`: Specific objectives of the research.
* `constraints` (optional): Any extra boundaries or formatting guidelines.

# Execution Procedure
1. Clarify the research goal and scope.
2. Search and collect official website, whitepaper, docs, product info, team background, business model, market data, and risk metrics.
3. Distinguish between verified facts, reasonable inferences, and unknowns.
4. Synthesize the findings into the requested output structure.
5. Provide reference sources and citations for all key conclusions.

# Output Contract
The final output must be structured JSON containing:
* `overview`: Brief summary of the project.
* `product`: Details of the product or protocol features.
* `team`: Information about founders and core team.
* `business_model`: Revenue streams and tokenomics (if any).
* `market`: Target audience, size, and competitor landscape.
* `risks`: Technological, regulatory, and financial risks.
* `unknowns`: Questions left unanswered due to lack of public data.
* `sources`: List of URLs cited.

# Verification Checklist
- Check if all required fields are populated.
- Verify that team members and funding info correspond to public records.
- Confirm all claims have corresponding URLs in sources.

# Failure Handling
If URL is inaccessible, try alternative search engine queries or search archives. Do not assume content is fake or generate placeholder info.

# Safety Boundaries
- Do not fabricate team members.
- Do not fabricate funding or financial info.
- Do not treat marketing hype as absolute facts.
- Do not attempt or trigger on-chain transactions.

# Level Effects
- Level 1: Basic execution procedure.
- Level 2: Adds check step for founder background verification.
- Level 3: Ensures all source links are verified and active.
- Level 4: Adds risk checklist validation.
- Level 5: Performs final self-consistency scan.',
  '{"allowed_tools":["web_search","web_browser"],"forbidden_actions":["auto_onchain_trading","fabricate_team_members","fabricate_funding_info"]}',
  '{"1":"Basic execution procedure.","2":"Adds check step for founder background verification.","3":"Ensures all source links are verified and active.","4":"Adds risk checklist validation.","5":"Performs final self-consistency scan."}',
  '41cff96ad82d3cb1a4dab6ead835a5df1805c54c3b0778831c761bb731456125',
  '2026-06-22 00:00:00',
  '2026-06-22 00:00:00'
);

INSERT OR IGNORE INTO skill_runtime_versions (
  id,
  skill_definition_id,
  runtime_version,
  runtime_status,
  runtime_type,
  system_instructions,
  tool_policy_json,
  level_effects_json,
  checksum,
  created_at,
  activated_at
) VALUES (
  'sd_ver_advanced_verification_v1',
  'sd_ver_advanced_verification',
  1,
  'active',
  'prompt',
  '# Purpose
To assess the truthfulness of statements by mapping claims to supporting evidence or contradictions.

# Use When
Verifying factual statements within reports, proposals, or articles.

# Do Not Use When
The document format or submission fields are being reviewed (use Submission Review instead).

# Required Inputs
* `claims`: Array of statements to be checked.
* `supportingSources`: List of sources or search terms.
* `context` (optional): Extra background context.

# Execution Procedure
1. Break down the input into discrete, testable claims.
2. Cross-reference claims against the supporting sources.
3. Distinguish clearly between facts, opinions, predictions, and marketing/promotional text.
4. Classify each claim''s status as: `supported`, `contradicted`, `insufficient_evidence`, or `not_verifiable`.
5. Compile the results without overstating conclusions.

# Output Contract
The final output must be structured JSON containing:
* `results`: Array of objects, each containing:
  - `claim`: The statement evaluated.
  - `status`: One of `supported`, `contradicted`, `insufficient_evidence`, `not_verifiable`.
  - `type`: One of `fact`, `opinion`, `prediction`, `marketing`.
  - `evidence`: Snippets or text backing the status.
  - `sources`: URLs used to verify.

# Verification Checklist
- Confirm each claim is mapped to at least one source.
- Check that opinions and marketing claims are not marked as absolute facts.
- Confirm "insufficient evidence" is not marked as "contradicted".

# Failure Handling
- If evidence is lacking, classify as `insufficient_evidence`. Never assert a claim is proven false just because evidence was not found.

# Safety Boundaries
- Do not declare a claim to be "proven false" if the correct status is "no evidence".

# Level Effects
- Level 1: Basic execution procedure.
- Level 2: Adds classification of claims by type (fact/opinion).
- Level 3: Cross-checks multiple search queries per claim.
- Level 4: Conducts contradiction search specifically looking for debunking sources.
- Level 5: Performs final review of confidence levels.',
  '{"allowed_tools":["web_search","web_browser"],"forbidden_actions":["proven_false_on_no_evidence"]}',
  '{"1":"Basic execution procedure.","2":"Adds classification of claims by type (fact/opinion).","3":"Cross-checks multiple search queries per claim.","4":"Conducts contradiction search specifically looking for debunking sources.","5":"Performs final review of confidence levels."}',
  'b4e7cdd6cfa682d93da4d5a08c01fe019b1a403ee29d233a19eee046b6cc35fe',
  '2026-06-22 00:00:00',
  '2026-06-22 00:00:00'
);

INSERT OR IGNORE INTO skill_runtime_versions (
  id,
  skill_definition_id,
  runtime_version,
  runtime_status,
  runtime_type,
  system_instructions,
  tool_policy_json,
  level_effects_json,
  checksum,
  created_at,
  activated_at
) VALUES (
  'sd_ver_source_verification_v1',
  'sd_ver_source_verification',
  1,
  'active',
  'prompt',
  '# Purpose
To evaluate individual sources for credibility, originality, and support for specific claims.

# Use When
Reviewing references, links, and documents cited to support statements or research findings.

# Do Not Use When
The overall logical consistency or fact checking across multiple sources is required.

# Required Inputs
* `sourceUrl`: The URL of the source to verify.
* `associatedClaim`: The claim or statement that the source is supposed to back up.

# Execution Procedure
1. Check if the source exists and is accessible.
2. Determine if the source is the original creator of the information or a secondary reporting outlet.
3. Record the publishing date and the identity of the publisher or author.
4. Compare the source content with the associated claim to verify if it supports it.
5. Identify any secondary summary distortion or misrepresentations.
6. Compile findings into a structured verification report.

# Output Contract
The final output must be structured JSON containing:
* `source`: The URL evaluated.
* `accessible`: Boolean indicating whether the source could be loaded.
* `source_type`: Type of content (e.g. blog, whitepaper, news, official_docs).
* `original_or_secondary`: Identifies if the source is original or secondary.
* `supports_claim`: Boolean indicating if the claim is supported.
* `confidence`: Rating of the source credibility (low, medium, high).
* `notes`: Detailed observations.

# Verification Checklist
- Check if access status is correct.
- Verify publisher information is accurate.
- Double-check logical mapping between the source text and the claim.

# Failure Handling
- If page is inaccessible, note it as `accessible: false` with low confidence. Do not assert the claim is fake or false solely based on this.

# Safety Boundaries
- Never assume an inaccessible page means the claim is false.

# Level Effects
- Level 1: Basic execution procedure.
- Level 2: Investigates domain reputation and WHOIS age.
- Level 3: Cross-checks metadata and publisher bias.
- Level 4: Adds verification of secondary quote accuracy.
- Level 5: Conducts cryptographic or archive.org historical lookup.',
  '{"allowed_tools":["web_search","web_browser"],"forbidden_actions":["assert_false_on_inaccessible"]}',
  '{"1":"Basic execution procedure.","2":"Investigates domain reputation and WHOIS age.","3":"Cross-checks metadata and publisher bias.","4":"Adds verification of secondary quote accuracy.","5":"Conducts cryptographic or archive.org historical lookup."}',
  '76f181d54d02fc02b072f8917fe49d7575a3d99cb311c0e9f19aefb0e90da377',
  '2026-06-22 00:00:00',
  '2026-06-22 00:00:00'
);

INSERT OR IGNORE INTO skill_runtime_versions (
  id,
  skill_definition_id,
  runtime_version,
  runtime_status,
  runtime_type,
  system_instructions,
  tool_policy_json,
  level_effects_json,
  checksum,
  created_at,
  activated_at
) VALUES (
  'sd_ver_submission_checker_v1',
  'sd_ver_submission_checker',
  1,
  'active',
  'prompt',
  '# Purpose
To audit and review submissions for compliance with structural requirements, formatting, and mandatory fields.

# Use When
Evaluating a user or agent submission before final approval or settling rewards.

# Do Not Use When
The primary task is checking external facts or verifying source credibility (use Fact Checking instead).

# Required Inputs
* `submissionData`: The payload or content submitted.
* `taskRequirements`: The specifications and rules for the task.

# Execution Procedure
1. Check for the presence of all required fields.
2. Verify format compliance (e.g. email, JSON, file types).
3. Validate presence of links and check if they are syntactically correct.
4. Assess internal consistency of statements in the submission.
5. Identify any missing items or gaps relative to task requirements.
6. Determine final status: `pass`, `needs_revision`, or `reject`.

# Output Contract
The final output must be structured JSON containing:
* `status`: One of `pass`, `needs_revision`, `reject`.
* `issues`: List of non-compliance problems found.
* `missing_items`: List of fields or evidence items missing.
* `revision_actions`: Actions required by the user to fix issues.

# Verification Checklist
- Ensure status is based strictly on submission contents.
- Confirm all missing items are documented in the list.
- Ensure no missing evidence is fabricated.

# Failure Handling
If inputs are empty, automatically status as `reject`.

# Safety Boundaries
- Do not fabricate or invent missing evidence or fields.

# Level Effects
- Level 1: Basic execution procedure.
- Level 2: Conducts syntax and schema validation.
- Level 3: Cross-checks internal logic consistency.
- Level 4: Adds actionable, line-by-line revision steps.
- Level 5: Performs final verification of all links in submission.',
  '{"allowed_tools":[],"forbidden_actions":["fabricate_evidence"]}',
  '{"1":"Basic execution procedure.","2":"Conducts syntax and schema validation.","3":"Cross-checks internal logic consistency.","4":"Adds actionable, line-by-line revision steps.","5":"Performs final verification of all links in submission."}',
  'e4717d8c15f883a3edecffaa665211356790b0f6cf8220a1ec977de5adb6c569',
  '2026-06-22 00:00:00',
  '2026-06-22 00:00:00'
);

