-- production-d1-remediation-history-v1.sql

-- Generated by scripts/build-production-d1-remediation.mjs - DO NOT EDIT MANUALLY

-- Purpose: backfill d1_migrations only after the custom remediation schema post-state is verified.



CREATE TABLE production_remediation_history_assertions (
  assertion_name TEXT PRIMARY KEY,
  is_valid INTEGER NOT NULL CHECK (is_valid = 1),
  reason TEXT NOT NULL
);

INSERT INTO production_remediation_history_assertions VALUES (
  'history table exists',
  CASE WHEN EXISTS (SELECT 1 FROM sqlite_master WHERE type='table' AND name='d1_migrations') THEN 1 ELSE 0 END,
  'history remediation blocked: d1_migrations table is missing'
);

INSERT INTO production_remediation_history_assertions VALUES (
  'history count still 5 before backfill',
  CASE WHEN (SELECT COUNT(*) FROM d1_migrations) = 5 THEN 1 ELSE 0 END,
  'history remediation blocked: expected exactly 5 rows before backfill'
);

INSERT INTO production_remediation_history_assertions VALUES (
  'history max still 5 before backfill',
  CASE WHEN (SELECT COALESCE(MAX(id), 0) FROM d1_migrations) = 5 THEN 1 ELSE 0 END,
  'history remediation blocked: expected max id 5 before backfill'
);

INSERT INTO production_remediation_history_assertions VALUES (
  '0012 updated_at present',
  CASE WHEN EXISTS (SELECT 1 FROM pragma_table_info('agent_skill_operations') WHERE name='updated_at') THEN 1 ELSE 0 END,
  'history remediation blocked: 0012 schema is incomplete'
);

INSERT INTO production_remediation_history_assertions VALUES (
  '0012 request_hash present',
  CASE WHEN EXISTS (SELECT 1 FROM pragma_table_info('box_orders') WHERE name='request_hash') THEN 1 ELSE 0 END,
  'history remediation blocked: box_orders.request_hash is still missing'
);

INSERT INTO production_remediation_history_assertions VALUES (
  '0013 canonical rules complete',
  CASE WHEN (SELECT COUNT(*) FROM skill_acquisition_rules WHERE is_canonical=1) = 31 THEN 1 ELSE 0 END,
  'history remediation blocked: canonical acquisition rules are incomplete'
);

INSERT INTO production_remediation_history_assertions VALUES (
  '0014 active runtimes complete',
  CASE WHEN (SELECT COUNT(*) FROM skill_runtime_versions WHERE runtime_status='active') = 31 THEN 1 ELSE 0 END,
  'history remediation blocked: active runtime versions are incomplete'
);

INSERT INTO production_remediation_history_assertions VALUES (
  '0015 execution_mode present',
  CASE WHEN EXISTS (SELECT 1 FROM pragma_table_info('agent_work_runs') WHERE name='execution_mode') THEN 1 ELSE 0 END,
  'history remediation blocked: execution_mode column is missing'
);

INSERT INTO production_remediation_history_assertions VALUES (
  '0016 research brief column present',
  CASE WHEN EXISTS (SELECT 1 FROM pragma_table_info('agent_work_runs') WHERE name='research_brief_result_json') THEN 1 ELSE 0 END,
  'history remediation blocked: research_brief_result_json column is missing'
);

INSERT INTO production_remediation_history_assertions VALUES (
  '0017 audit table present',
  CASE WHEN EXISTS (SELECT 1 FROM sqlite_master WHERE type='table' AND name='admin_risk_audit_events') THEN 1 ELSE 0 END,
  'history remediation blocked: admin_risk_audit_events table is missing'
);



INSERT INTO d1_migrations (id, name, applied_at)
SELECT 6, '0006_agent_workflow_box_store_wallet.sql', CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM d1_migrations WHERE id = 6);

INSERT INTO d1_migrations (id, name, applied_at)
SELECT 7, '0007_seed_v1_catalog_and_store.sql', CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM d1_migrations WHERE id = 7);

INSERT INTO d1_migrations (id, name, applied_at)
SELECT 8, '0008_v1_rigorous_constraints.sql', CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM d1_migrations WHERE id = 8);

INSERT INTO d1_migrations (id, name, applied_at)
SELECT 9, '0009_v1_constraints_and_reservations.sql', CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM d1_migrations WHERE id = 9);

INSERT INTO d1_migrations (id, name, applied_at)
SELECT 10, '0010_box_openings_owner_constraint.sql', CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM d1_migrations WHERE id = 10);

INSERT INTO d1_migrations (id, name, applied_at)
SELECT 11, '0011_agent_skill_core.sql', CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM d1_migrations WHERE id = 11);

INSERT INTO d1_migrations (id, name, applied_at)
SELECT 12, '0012_skill_economy_loop.sql', CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM d1_migrations WHERE id = 12);

INSERT INTO d1_migrations (id, name, applied_at)
SELECT 13, '0013_skill_catalog_acquisition_v1.sql', CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM d1_migrations WHERE id = 13);

INSERT INTO d1_migrations (id, name, applied_at)
SELECT 14, '0014_skill_runtime_lite_v1.sql', CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM d1_migrations WHERE id = 14);

INSERT INTO d1_migrations (id, name, applied_at)
SELECT 15, '0015_workflow_runtime_settlement_gate.sql', CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM d1_migrations WHERE id = 15);

INSERT INTO d1_migrations (id, name, applied_at)
SELECT 16, '0016_research_brief_runtime_v1.sql', CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM d1_migrations WHERE id = 16);

INSERT INTO d1_migrations (id, name, applied_at)
SELECT 17, '0017_real_asset_agent_persistence_v1.sql', CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM d1_migrations WHERE id = 17);



CREATE TABLE production_remediation_history_post_assertions (
  assertion_name TEXT PRIMARY KEY,
  is_valid INTEGER NOT NULL CHECK (is_valid = 1),
  reason TEXT NOT NULL
);

INSERT INTO production_remediation_history_post_assertions VALUES (
  'history row count is 17',
  CASE WHEN (SELECT COUNT(*) FROM d1_migrations) = 17 THEN 1 ELSE 0 END,
  'history remediation blocked: expected exactly 17 history rows after backfill'
);

INSERT INTO production_remediation_history_post_assertions VALUES (
  'history max id is 17',
  CASE WHEN (SELECT COALESCE(MAX(id), 0) FROM d1_migrations) = 17 THEN 1 ELSE 0 END,
  'history remediation blocked: expected max id 17 after backfill'
);



DROP TABLE production_remediation_history_post_assertions;

DROP TABLE production_remediation_history_assertions;